export const mockTransactions = {
  user1: [
    { id: "u1-t1", amount: "850.00", category: "Food", currency: "INR", date: "2025-05-12", method: "UPI", name: "Dominos", status: "Successful", type: "Expense" },
    { id: "u1-t2", amount: "3200.00", category: "Shopping", currency: "INR", date: "2025-06-04", method: "Card", name: "Amazon", status: "Successful", type: "Expense" },
    { id: "u1-t3", amount: "12000.00", category: "Salary", currency: "INR", date: "2025-06-30", method: "Bank", name: "Company", status: "Successful", type: "Income" },
    { id: "u1-t4", amount: "540.00", category: "Transport", currency: "INR", date: "2025-07-08", method: "UPI", name: "Uber", status: "Successful", type: "Expense" },
    { id: "u1-t5", amount: "1800.00", category: "Food", currency: "INR", date: "2025-07-15", method: "UPI", name: "Swiggy", status: "Successful", type: "Expense" },
    { id: "u1-t6", amount: "6200.00", category: "Rent", currency: "INR", date: "2025-08-01", method: "Bank", name: "Landlord", status: "Successful", type: "Expense" },
    { id: "u1-t7", amount: "900.00", category: "Entertainment", currency: "INR", date: "2025-08-21", method: "Card", name: "Netflix", status: "Successful", type: "Expense" },
    { id: "u1-t8", amount: "13500.00", category: "Salary", currency: "INR", date: "2025-09-30", method: "Bank", name: "Company", status: "Successful", type: "Income" },
    { id: "u1-t9", amount: "420.00", category: "Food", currency: "INR", date: "2025-10-05", method: "UPI", name: "Cafe", status: "Successful", type: "Expense" },
    { id: "u1-t10", amount: "2800.00", category: "Shopping", currency: "INR", date: "2025-10-18", method: "Card", name: "Flipkart", status: "Successful", type: "Expense" },
    { id: "u1-t11", amount: "7200.00", category: "Rent", currency: "INR", date: "2025-11-01", method: "Bank", name: "Landlord", status: "Successful", type: "Expense" },
    { id: "u1-t12", amount: "15000.00", category: "Salary", currency: "INR", date: "2025-11-30", method: "Bank", name: "Company", status: "Successful", type: "Income" },
    { id: "u1-t13", amount: "600.00", category: "Transport", currency: "INR", date: "2025-12-09", method: "UPI", name: "Metro", status: "Successful", type: "Expense" },
    { id: "u1-t14", amount: "2000.00", category: "Food", currency: "INR", date: "2025-12-25", method: "UPI", name: "Party", status: "Successful", type: "Expense" },
    { id: "u1-t15", amount: "16000.00", category: "Salary", currency: "INR", date: "2026-01-30", method: "Bank", name: "Company", status: "Successful", type: "Income" },
    { id: "u1-t16", amount: "950.00", category: "Food", currency: "INR", date: "2026-02-04", method: "UPI", name: "KFC", status: "Successful", type: "Expense" },
    { id: "u1-t17", amount: "3800.00", category: "Shopping", currency: "INR", date: "2026-02-18", method: "Card", name: "Myntra", status: "Successful", type: "Expense" },
    { id: "u1-t18", amount: "17500.00", category: "Salary", currency: "INR", date: "2026-03-30", method: "Bank", name: "Company", status: "Successful", type: "Income" },
    { id: "u1-t19", amount: "700.00", category: "Transport", currency: "INR", date: "2026-04-02", method: "UPI", name: "Auto", status: "Successful", type: "Expense" },
    { id: "u1-t20", amount: "2200.00", category: "Food", currency: "INR", date: "2026-04-05", method: "UPI", name: "Restaurant", status: "Successful", type: "Expense" },
    { id: "u1-t22", amount: "1200.00", category: "Shopping", currency: "INR", date: "2026-04-08", method: "Card", name: "Uniqlo", status: "Successful", type: "Expense" },
    { id: "u1-t23", amount: "550.00", category: "Transport", currency: "INR", date: "2026-04-10", method: "UPI", name: "Uber", status: "Successful", type: "Expense" },
    { id: "u1-t24", amount: "3200.00", category: "Food", currency: "INR", date: "2026-04-12", method: "UPI", name: "Party Dinner", status: "Successful", type: "Expense" },
    { id: "u1-t25", amount: "6200.00", category: "Rent", currency: "INR", date: "2026-04-15", method: "Bank", name: "Landlord", status: "Successful", type: "Expense" },
    { id: "u1-t26", amount: "890.00", category: "Entertainment", currency: "INR", date: "2026-04-18", method: "Card", name: "Movie Ticket", status: "Successful", type: "Expense" },
    { id: "u1-t27", amount: "1450.00", category: "Food", currency: "INR", date: "2026-04-20", method: "UPI", name: "Swiggy", status: "Successful", type: "Expense" },
    { id: "u1-t28", amount: "2800.00", category: "Shopping", currency: "INR", date: "2026-04-22", method: "Card", name: "Flipkart", status: "Successful", type: "Expense" },
    { id: "u1-t29", amount: "625.00", category: "Transport", currency: "INR", date: "2026-04-25", method: "UPI", name: "Metro", status: "Successful", type: "Expense" },
    { id: "u1-t30", amount: "1850.00", category: "Food", currency: "INR", date: "2026-04-27", method: "UPI", name: "Lunch", status: "Successful", type: "Expense" },
    { id: "u1-t31", amount: "4500.00", category: "Shopping", currency: "INR", date: "2026-04-29", method: "Card", name: "Amazon", status: "Successful", type: "Expense" },
    { id: "u1-t21", amount: "18500.00", category: "Salary", currency: "INR", date: "2026-04-30", method: "Bank", name: "Company", status: "Successful", type: "Income" }
  ],

  user2: [
    { id: "u2-t1", amount: "500.00", category: "Food", currency: "INR", date: "2025-05-10", method: "UPI", name: "Cafe", status: "Successful", type: "Expense" },
    { id: "u2-t2", amount: "8000.00", category: "Freelance", currency: "INR", date: "2025-05-28", method: "Bank", name: "Client", status: "Successful", type: "Income" },
    { id: "u2-t3", amount: "4500.00", category: "Shopping", currency: "INR", date: "2025-06-15", method: "Card", name: "Ajio", status: "Successful", type: "Expense" },
    { id: "u2-t4", amount: "900.00", category: "Transport", currency: "INR", date: "2025-07-05", method: "UPI", name: "Ola", status: "Successful", type: "Expense" },
    { id: "u2-t5", amount: "11000.00", category: "Freelance", currency: "INR", date: "2025-07-29", method: "Bank", name: "Client", status: "Successful", type: "Income" },
    { id: "u2-t6", amount: "2500.00", category: "Food", currency: "INR", date: "2025-08-20", method: "UPI", name: "Swiggy", status: "Successful", type: "Expense" },
    { id: "u2-t7", amount: "6000.00", category: "Investment", currency: "INR", date: "2025-09-12", method: "Bank", name: "Stocks", status: "Successful", type: "Expense" },
    { id: "u2-t8", amount: "15000.00", category: "Freelance", currency: "INR", date: "2025-10-30", method: "Bank", name: "Client", status: "Successful", type: "Income" },
    { id: "u2-t9", amount: "1000.00", category: "Entertainment", currency: "INR", date: "2025-11-11", method: "Card", name: "Prime", status: "Successful", type: "Expense" },
    { id: "u2-t10", amount: "700.00", category: "Transport", currency: "INR", date: "2025-12-06", method: "UPI", name: "Metro", status: "Successful", type: "Expense" },
    { id: "u2-t11", amount: "17000.00", category: "Freelance", currency: "INR", date: "2026-01-28", method: "Bank", name: "Client", status: "Successful", type: "Income" },
    { id: "u2-t12", amount: "4200.00", category: "Shopping", currency: "INR", date: "2026-02-08", method: "Card", name: "Flipkart", status: "Successful", type: "Expense" },
    { id: "u2-t13", amount: "950.00", category: "Food", currency: "INR", date: "2026-02-18", method: "UPI", name: "Cafe", status: "Successful", type: "Expense" },
    { id: "u2-t14", amount: "12000.00", category: "Freelance", currency: "INR", date: "2026-03-26", method: "Bank", name: "Client", status: "Successful", type: "Income" },
    { id: "u2-t15", amount: "3000.00", category: "Investment", currency: "INR", date: "2026-04-02", method: "Bank", name: "Mutual Fund", status: "Successful", type: "Expense" },
    { id: "u2-t16", amount: "1800.00", category: "Food", currency: "INR", date: "2026-04-05", method: "UPI", name: "Dinner", status: "Successful", type: "Expense" },
    { id: "u2-t22", amount: "2000.00", category: "Shopping", currency: "INR", date: "2026-04-07", method: "Card", name: "Myntra", status: "Successful", type: "Expense" },
    { id: "u2-t23", amount: "800.00", category: "Transport", currency: "INR", date: "2026-04-09", method: "UPI", name: "Ola", status: "Successful", type: "Expense" },
    { id: "u2-t24", amount: "1500.00", category: "Food", currency: "INR", date: "2026-04-11", method: "UPI", name: "Cafe", status: "Successful", type: "Expense" },
    { id: "u2-t25", amount: "3500.00", category: "Investment", currency: "INR", date: "2026-04-13", method: "Bank", name: "Mutual Fund", status: "Successful", type: "Expense" },
    { id: "u2-t26", amount: "1100.00", category: "Entertainment", currency: "INR", date: "2026-04-16", method: "Card", name: "Amazon Prime", status: "Successful", type: "Expense" },
    { id: "u2-t27", amount: "2200.00", category: "Food", currency: "INR", date: "2026-04-19", method: "UPI", name: "Swiggy", status: "Successful", type: "Expense" },
    { id: "u2-t28", amount: "1900.00", category: "Shopping", currency: "INR", date: "2026-04-21", method: "Card", name: "Flipkart", status: "Successful", type: "Expense" },
    { id: "u2-t29", amount: "650.00", category: "Transport", currency: "INR", date: "2026-04-23", method: "UPI", name: "Metro", status: "Successful", type: "Expense" },
    { id: "u2-t30", amount: "1400.00", category: "Food", currency: "INR", date: "2026-04-26", method: "UPI", name: "Brunch", status: "Successful", type: "Expense" },
    { id: "u2-t31", amount: "2700.00", category: "Shopping", currency: "INR", date: "2026-04-29", method: "Card", name: "Amazon", status: "Successful", type: "Expense" },
    { id: "u2-t21", amount: "12500.00", category: "Freelance", currency: "INR", date: "2026-04-28", method: "Bank", name: "Client", status: "Successful", type: "Income" }
  ],

  user3: [
    { id: "u3-t1", amount: "15000", category: "Salary", currency: "INR", date: "2025-05-30", method: "Bank", name: "Company", status: "Successful", type: "Income" },
    { id: "u3-t2", amount: "3500", category: "Rent", currency: "INR", date: "2025-06-01", method: "Bank", name: "Owner", status: "Successful", type: "Expense" },
    { id: "u3-t3", amount: "1200", category: "Food", currency: "INR", date: "2025-06-18", method: "UPI", name: "Zomato", status: "Successful", type: "Expense" },
    { id: "u3-t4", amount: "900", category: "Transport", currency: "INR", date: "2025-07-07", method: "UPI", name: "Metro", status: "Successful", type: "Expense" },
    { id: "u3-t5", amount: "16000", category: "Salary", currency: "INR", date: "2025-07-30", method: "Bank", name: "Company", status: "Successful", type: "Income" },
    { id: "u3-t6", amount: "5000", category: "Shopping", currency: "INR", date: "2025-08-12", method: "Card", name: "Mall", status: "Successful", type: "Expense" },
    { id: "u3-t7", amount: "800", category: "Food", currency: "INR", date: "2025-09-03", method: "UPI", name: "Cafe", status: "Successful", type: "Expense" },
    { id: "u3-t8", amount: "17000", category: "Salary", currency: "INR", date: "2025-09-30", method: "Bank", name: "Company", status: "Successful", type: "Income" },
    { id: "u3-t9", amount: "2000", category: "Entertainment", currency: "INR", date: "2025-10-14", method: "Card", name: "Movies", status: "Successful", type: "Expense" },
    { id: "u3-t10", amount: "4500", category: "Rent", currency: "INR", date: "2025-11-01", method: "Bank", name: "Owner", status: "Successful", type: "Expense" },
    { id: "u3-t11", amount: "18000", category: "Salary", currency: "INR", date: "2025-11-30", method: "Bank", name: "Company", status: "Successful", type: "Income" },
    { id: "u3-t12", amount: "950", category: "Food", currency: "INR", date: "2025-12-22", method: "UPI", name: "Dinner", status: "Successful", type: "Expense" },
    { id: "u3-t13", amount: "6000", category: "Shopping", currency: "INR", date: "2026-01-10", method: "Card", name: "Amazon", status: "Successful", type: "Expense" },
    { id: "u3-t14", amount: "20000", category: "Salary", currency: "INR", date: "2026-01-30", method: "Bank", name: "Company", status: "Successful", type: "Income" },
    { id: "u3-t15", amount: "700", category: "Transport", currency: "INR", date: "2026-02-08", method: "UPI", name: "Auto", status: "Successful", type: "Expense" },
    { id: "u3-t16", amount: "21000", category: "Salary", currency: "INR", date: "2026-02-28", method: "Bank", name: "Company", status: "Successful", type: "Income" },
    { id: "u3-t17", amount: "1500", category: "Food", currency: "INR", date: "2026-03-12", method: "UPI", name: "Restaurant", status: "Successful", type: "Expense" },
    { id: "u3-t18", amount: "22000", category: "Salary", currency: "INR", date: "2026-03-30", method: "Bank", name: "Company", status: "Successful", type: "Income" },
    { id: "u3-t19", amount: "3000", category: "Shopping", currency: "INR", date: "2026-04-01", method: "Card", name: "Flipkart", status: "Successful", type: "Expense" },
    { id: "u3-t20", amount: "1100", category: "Food", currency: "INR", date: "2026-04-05", method: "UPI", name: "Lunch", status: "Successful", type: "Expense" },
    { id: "u3-t22", amount: "2500", category: "Shopping", currency: "INR", date: "2026-04-06", method: "Card", name: "Ajio", status: "Successful", type: "Expense" },
    { id: "u3-t23", amount: "700", category: "Transport", currency: "INR", date: "2026-04-08", method: "UPI", name: "Auto", status: "Successful", type: "Expense" },
    { id: "u3-t24", amount: "1800", category: "Food", currency: "INR", date: "2026-04-10", method: "UPI", name: "Zomato", status: "Successful", type: "Expense" },
    { id: "u3-t25", amount: "4500", category: "Rent", currency: "INR", date: "2026-04-14", method: "Bank", name: "Owner", status: "Successful", type: "Expense" },
    { id: "u3-t26", amount: "950", category: "Entertainment", currency: "INR", date: "2026-04-17", method: "Card", name: "Concert", status: "Successful", type: "Expense" },
    { id: "u3-t27", amount: "1600", category: "Food", currency: "INR", date: "2026-04-19", method: "UPI", name: "Dinner", status: "Successful", type: "Expense" },
    { id: "u3-t28", amount: "3200", category: "Shopping", currency: "INR", date: "2026-04-21", method: "Card", name: "Amazon", status: "Successful", type: "Expense" },
    { id: "u3-t29", amount: "800", category: "Transport", currency: "INR", date: "2026-04-24", method: "UPI", name: "Metro", status: "Successful", type: "Expense" },
    { id: "u3-t30", amount: "1250", category: "Food", currency: "INR", date: "2026-04-26", method: "UPI", name: "Cafe", status: "Successful", type: "Expense" },
    { id: "u3-t31", amount: "2000", category: "Shopping", currency: "INR", date: "2026-04-28", method: "Card", name: "Flipkart", status: "Successful", type: "Expense" },
    { id: "u3-t21", amount: "23000", category: "Salary", currency: "INR", date: "2026-04-30", method: "Bank", name: "Company", status: "Successful", type: "Income" }
  ]
};
export const mockBudgets = {
  user1: [
    { id: "b1", category: "Food", amount: 4000, createdAt: "2025-06-01", type: "Expense" },
    { id: "b2", category: "Shopping", amount: 7000, createdAt: "2025-07-01", type: "Expense" },
    { id: "b3", category: "Transport", amount: 2000, createdAt: "2025-08-01", type: "Expense" },
    { id: "b4", category: "Entertainment", amount: 1500, createdAt: "2025-09-01", type: "Expense" },
    { id: "b5", category: "Food", amount: 5000, createdAt: "2026-01-01", type: "Expense" },
    { id: "b6", category: "Shopping", amount: 8000, createdAt: "2026-02-01", type: "Expense" },
    { id: "b7", category: "Transport", amount: 2500, createdAt: "2026-03-01", type: "Expense" }
  ],

  user2: [
    { id: "b8", category: "Investment", amount: 6000, createdAt: "2025-07-01", type: "Expense" },
    { id: "b9", category: "Food", amount: 3000, createdAt: "2025-08-01", type: "Expense" },
    { id: "b10", category: "Shopping", amount: 5000, createdAt: "2025-10-01", type: "Expense" },
    { id: "b11", category: "Transport", amount: 1500, createdAt: "2026-02-01", type: "Expense" },
    { id: "b12", category: "Food", amount: 4500, createdAt: "2026-04-01", type: "Expense" }
  ],

  user3: [
    { id: "b13", category: "Rent", amount: 5000, createdAt: "2025-06-01", type: "Expense" },
    { id: "b14", category: "Food", amount: 2500, createdAt: "2025-09-01", type: "Expense" },
    { id: "b15", category: "Shopping", amount: 6000, createdAt: "2026-01-01", type: "Expense" },
    { id: "b16", category: "Entertainment", amount: 2000, createdAt: "2026-03-01", type: "Expense" }
  ]
};
